improved script

diff --git a/rebuild-all b/rebuild-all
--- a/rebuild-all
+++ b/rebuild-all
@@ -7,6 +7,16 @@ prefix="${wd}/../usr/local/"
 dirs='ticcutils timbl timblserver mbt mbtserver dimbl libfolia ucto frogdata frog foliatools ticcltools toad wopr tscan'
 exes='timbl timblserver mbt mbtserver dimbl ucto frog FoLiA-stats FoLiA-alto FoLiA-hocr TICCL-lexclean TICCL-indexerNT wopr tscan'
 
+#sanity check
+for app in $dirs
+do
+    if ! test -d $app
+    then
+	echo "$app dir not found. Could become troublesome"
+	exit
+    fi
+done
+
 # configure and make all
 for app in $dirs
 do
