nicer output

diff --git a/redo-everything-from-scratch b/redo-everything-from-scratch
--- a/redo-everything-from-scratch
+++ b/redo-everything-from-scratch
@@ -1,10 +1,14 @@
 #! /bin/bash
 
+OK="\033[1;32m OK  \033[0m"
+FAIL="\033[1;31m  FAILED  \033[0m"
+
 echo "Rebuilding ALL"
 wd=`pwd`
 prefix="${wd}/../usr/local/"
 
-dirs='ticcutils timbl timblserver mbt mbtserver dimbl libfolia ucto frogdata frog foliautils ticcltools toad wopr tscan'
+#dirs='ticcutils timbl timblserver mbt mbtserver dimbl libfolia ucto frogdata frog foliautils ticcltools toad wopr tscan'
+dirs='ticcutils timbl timblserver'
 exes='timbl timblserver mbt mbtserver dimbl ucto frog FoLiA-stats FoLiA-alto FoLiA-hocr TICCL-lexclean TICCL-indexerNT wopr tscan'
 
 #sanity check
@@ -24,17 +28,49 @@ do
     then
 	name=$app
 	name=${name/\//_}
-	pushd $app
-	git pull
-	make maintainer-clean
+	pushd $app 1> ../$name.log 2>&1
+	echo -n "$app: updating"
+	git pull 1> ../$name.log 2>&1
+	if [ $? -ne 0 ];
+	then
+	    echo -e $FAIL
+	    popd
+	    echo "see $name.log"
+	    exit
+	fi
+	make maintainer-clean 1> ../$name.log 2>&1
 	rm -f config.{guess,sub}
-	sh ./bootstrap.sh
-	echo "configuring $app "
-	CXXFLAGS="-pedantic -W -Wall -O3 " ./configure --prefix=$prefix > ../$name.log 2>&1
-	echo "making $app"
-	make install >> ../$name.log 2>&1
-	echo "done $app"
-	popd
+	sh ./bootstrap.sh 1>> ../$name.log 2>&1
+	if [ $? -ne 0 ];
+	then
+	    echo -e $FAIL
+	    popd
+	    echo "see $name.log"
+	    exit
+	fi
+
+	echo -n ", configuring"
+	CXXFLAGS="-pedantic -W -Wall -O3 " ./configure --prefix=$prefix 1> ../$name.log 2>&1
+	if [ $? -ne 0 ];
+	then
+	    echo -e $FAIL
+	    popd
+	    echo "see $name.log"
+	    exit
+	fi
+
+	echo -n ", making"
+	make install 1>> ../$name.log 2>&1
+	if [ $? -ne 0 ];
+	then
+	    echo -e $FAIL
+	    popd
+	    echo "see $name.log"
+	    exit
+	else
+	    echo -e $OK
+	fi
+	popd  1> ../$name.log 2>&1
     else
 	echo "$app dir not found. Could become troublesome"
 	exit 1
@@ -46,7 +82,15 @@ for app in $exes
 do
     if test -x $prefix/bin/$app
     then
-	$prefix/bin/$app -V
+	$prefix/bin/$app -V  1> $name.log 2>&1
+	if [ $? -ne 0 ];
+	then
+	    echo -e $FAIL
+	    echo "see $name.log"
+	else
+	    echo -n "testing $app: "
+	    echo -e $OK
+	fi
     else
 	echo "couldn't find $app executable"
     fi
