improved

diff --git a/update-all b/update-all
--- a/update-all
+++ b/update-all
@@ -11,11 +11,19 @@ for app in $dirs
 do
     if [ -e $app/.git ]
     then
-	pushd $app
-	git pull
+	rm $app.log
+	pushd $app > /dev/null 2>1
+	git pull  > /dev/null 2>1
+	ech "building in $app"
 	if [ -e Makefile ]
 	then
-	    make install
+	    make install > ../$app.log 2>1
+	    if [ $? -ne 0 ]
+	    then
+		echo "$app failed: see $app.log"
+	    else
+		rm ../$app.log
+	    fi
 	else
 	    echo "No Makefile in $dir"
 	fi
